<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Practice Selenium level 1"
           tests="3"
           failures="2"
           errors="0"
           skipped="0"
           time="5.403">
    <properties></properties>

            <testcase
                name="TC001"
                time="2.151"
                classname="testcases.TestCases">

            <failure type="java.lang.AssertionError" message="expected [Wellcome h1uv4c9ktg@email2u.shop] but found []">
                <![CDATA[java.lang.AssertionError: expected [Wellcome h1uv4c9ktg@email2u.shop] but found []
                org.testng.Assert.fail(Assert.java:111)org.testng.Assert.failNotEquals(Assert.java:1578)org.testng.Assert.assertEqualsImpl(Assert.java:150)org.testng.Assert.assertEquals(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:656)org.testng.Assert.assertEquals(Assert.java:666)testcases.TestCases.TC001(TestCases.java:37)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:566)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </failure>
    </testcase>
            <testcase
                name="TC002"
                time="1.749"
                classname="testcases.TestCases">

            <failure type="java.lang.AssertionError" message="expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]">
                <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
                org.testng.Assert.fail(Assert.java:111)org.testng.Assert.failNotEquals(Assert.java:1578)org.testng.Assert.assertEqualsImpl(Assert.java:150)org.testng.Assert.assertEquals(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:656)org.testng.Assert.assertEquals(Assert.java:666)testcases.TestCases.TC002(TestCases.java:64)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:566)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </failure>
    </testcase>


            <testcase
                name="TC002"
                time="1.503"
                classname="testcases.TestCases">
            </testcase>
</testsuite>
